on:
    push:
        branches:
            - ci/update-locale

jobs:
    download:
        name: Synchronize with Crowdin
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Prettify code
              uses: creyD/prettier_action@v4.2
              with:
                  prettier_options: --write locale/*.ts
